---
- name: Create a new Zabbix user
  community.zabbix.zabbix_user:
    username: "{{ zabbix_api_user }}"
    passwd: "{{ zabbix_api_user_password }}"
    role_name: "Super admin role"
    usrgrps:
      - "Zabbix administrators"
    state: present