---
- name: Create a new Zabbix user
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: "{{ zabbix_server_main }}"
  community.zabbix.zabbix_user:
    username: "{{ zabbix_api_user }}"
    passwd: "{{ zabbix_api_user_password }}"
    role_name: "Super admin role"
    usrgrps:
      - "Zabbix administrators"
    state: present