---
- name: Add datasource
  community.grafana.grafana_datasource:
    name: Zabbix
    url: "192.168.1.3:3000"
    url_username: admin
    url_password: "{{ grafana_admin_password }}"
    ds_type: alexanderzobnin-zabbix-datasource
    ds_url: "http://192.168.1.2:8002/api_jsonrpc.php"
    access: proxy
    state: present
    secureJsonData:
      apiToken: "{{ lookup('ansible.builtin.file', '/opt/tokens/grafana_token.txt') }}"