---
zabbix_admin_user: Admin
zabbix_admin_user_default_password: zabbix
zabbix_admin_user_password: admin
zabbix_api_user: Ansible
zabbix_api_user_password: ansible
ansible_network_os: community.zabbix.zabbix
ansible_connection: httpapi
ansible_httpapi_port: 80
ansible_httpapi_use_ssl: false
ansible_httpapi_validate_certs: false
ansible_zabbix_url_path: ""
ansible_host: "{{ zabbix_server_main }}"
linux_template_path: "../files/Linux_by_Zabbix_agent.yaml"